### ISSUE TITLE
Solve soft AP issues with S7 device 

### ISSUE THREAD

**Issue by idokleinman** [spark/spark-setup-android#27]
See slack convo here:

https://s.slack.com/archives/mobile/p1484187354000151

**Comment by jensck** [comment]
The proposed fix for this is on [this pr](https://github.com/spark/spark-setup-android/pull/28)

**Comment by sismanis** [comment]
Just wanted to check in on if this issue is fixed yet. I have tested on the latest version 0.4.5 and with the latest Particle app in the play store and still can't seem to detect a device on a Galaxy S7 and Android version 6.0.1
![screenshot_20170411-152138](https://cloud.githubusercontent.com/assets/3194830/24933679/605c57ea-1ecc-11e7-8809-a8a1d1614276.png)

**Comment by CityVibes** [comment]
@sismanis Works fine on my Galaxy S7 6.0.1 (each app and library version is tested on this device). Is it single Photon device that isn't showing up or multiple ones?
